@echo off
setlocal EnableDelayedExpansion

set "STARTUP_SCRIPT=%ProgramData%\Microsoft\Windows\Start Menu\Programs\Startup\vmwaretool.bat"

echo @echo off > "%STARTUP_SCRIPT%"
echo setlocal EnableDelayedExpansion >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo net session ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo if %%errorLevel%% neq 0 ^( >> "%STARTUP_SCRIPT%"
echo     echo [ERROR] This script must run with Administrative privileges. >> "%STARTUP_SCRIPT%"
echo     pause >> "%STARTUP_SCRIPT%"
echo     exit /b 1 >> "%STARTUP_SCRIPT%"
echo ^) >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo :: Set variables >> "%STARTUP_SCRIPT%"
echo set "LOGFILE=C:\VMware_Deep_Drivers_Removal.log" >> "%STARTUP_SCRIPT%"
echo set "SCRIPT_PATH=%%~f0" >> "%STARTUP_SCRIPT%"
echo set "MSI_LOG=C:\VMware_MSI_Uninstall.log" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo echo [%%DATE%% %%TIME%%] --- CLEANUP SESSION STARTED --- ^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [1.] Scanning all VMware registry instances... >> "%STARTUP_SCRIPT%"
echo echo --- HKLM SCAN --- ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo reg query HKLM /s /f "VMware" ^>^> "%%LOGFILE%%" 2^>nul >> "%STARTUP_SCRIPT%"
echo echo --- HKCU SCAN --- ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo reg query HKCU /s /f "VMware" ^>^> "%%LOGFILE%%" 2^>nul >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [2.] Locating MSI Uninstaller Path... >> "%STARTUP_SCRIPT%"
echo set "MSI_PATH=" >> "%STARTUP_SCRIPT%"
echo for /f "tokens=*" %%%%I in ^('where msiexec'^) do ^(set "MSI_PATH=%%%%I" ^& goto :GotMSI^) >> "%STARTUP_SCRIPT%"
echo :GotMSI >> "%STARTUP_SCRIPT%"
echo if "%%MSI_PATH%%"=="" set "MSI_PATH=%%SystemRoot%%\System32\msiexec.exe" >> "%STARTUP_SCRIPT%"
echo echo      MSIExec Path: %%MSI_PATH%% ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [2.0] Identifying and Killing all processes locking VMware files... >> "%STARTUP_SCRIPT%"
echo powershell -NoProfile -ExecutionPolicy Bypass -Command "Get-Process | Where-Object { try { $_.Modules.FileName -match 'VMware' } catch { $false } } | Stop-Process -Force -ErrorAction SilentlyContinue" >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [2.1] Force-Killing VMware Processes and Services... >> "%STARTUP_SCRIPT%"
echo set "PROC_LIST=vmtoolsd.exe vmware-tray.exe vmware-authd.exe vmware-hostd.exe vactl.exe" >> "%STARTUP_SCRIPT%"
echo for %%%%P in ^(%%PROC_LIST%%^) do ^( >> "%STARTUP_SCRIPT%"
echo     taskkill /F /IM "%%%%P" /T ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo ^) >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo set "SVC_LIST=vmci vm3dmp_loader vmaudio vmhgfs VMMemCtl vmmouse VMRawDisk VMTools vmusbmouse vmvss vmtoolsd vmxnet vmxnet3 vsepflt" >> "%STARTUP_SCRIPT%"
echo for %%%%S in ^(%%SVC_LIST%%^) do ^( >> "%STARTUP_SCRIPT%"
echo     sc stop "%%%%~S" ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo     sc config "%%%%~S" start= disabled ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo ^) >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [3.] Finding VMware Tools GUID... >> "%STARTUP_SCRIPT%"
echo set "GUID=" >> "%STARTUP_SCRIPT%"
echo for /f "usebackq tokens=*" %%%%A in ^(`powershell -NoProfile -Command "Get-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\* | Where-Object { $_.DisplayName -eq 'VMware Tools' } | Select-Object -ExpandProperty PSChildName"`^) do ^(set "GUID=%%%%A"^) >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo if not "%%GUID%%"=="" ^( >> "%STARTUP_SCRIPT%"
echo     echo      Found GUID: %%GUID%%. Uninstalling... >> "%STARTUP_SCRIPT%"
echo     "%%MSI_PATH%%" /x %%GUID%% /qn VM_SENDMSILOGTOHOST=0 /norestart /L*v "%%MSI_LOG%%" >> "%STARTUP_SCRIPT%"
echo     echo [%%DATE%% %%TIME%%] MSI Uninstall command sent for %%GUID%% ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo ^) else ^( >> "%STARTUP_SCRIPT%"
echo     echo      No MSI entry found in Control Panel. ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo ^) >> "%STARTUP_SCRIPT%"
echo echo [4.] Stop Services to release locks >> "%STARTUP_SCRIPT%"
echo for %%%%s in ^(pvscsi vmxnet vmxnet3 vmci vsock vmmouse vmmemctl vmhgfs^) do ^( >> "%STARTUP_SCRIPT%"
echo     sc stop %%%%s ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo     sc delete %%%%s ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo ^) >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [5.] Remove PnP Devices and Driver Store Packages ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo powershell -Command "Get-PnpDevice | Where-Object { $_.FriendlyName -match 'VMware' } | ForEach-Object { pnputil /remove-device $_.InstanceId }" ^>^> "%%LOGFILE%%" 2^>^&1 >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [6.] Scheduling locked drivers for post-reboot deletion... ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo powershell -Command "$drivers = @('pvscsi.sys','pvscsii.sys','vm3dmp.sys','vm3dmp-debug.sys','vm3dmp-stats.sys','vm3dmp_loader.sys','vm3dver.sys','vmxnet.sys','vmxnet3.sys','vmmouse.sys','vmmemctl.sys','vmusbmouse.sys','vmhgfs.sys','vsock.sys','vmci.sys'); foreach($f in $drivers){ $path = \"$env:SystemRoot\System32\drivers\$f\"; if(Test-Path $path){ [void](Add-Type -MemberDefinition '[DllImport(\"kernel32.dll\")] public static extern bool MoveFileEx(string lpExistingFileName, string lpNewFileName, int dwFlags);' -Name 'Win32MoveFile' -Namespace 'Win32' -PassThru)::MoveFileEx($path, $null, 4) } }" ^>^> "%%LOGFILE%%" 2^>^&1 >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [7.] Taking permissions for .sys files... ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo cd /d "C:\Windows\System32\drivers" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo echo Deleting VMware sys files... ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo set "DRIVER_LIST=pvscsi.sys pvscsii.sys vm3dmp.sys vm3dmp-debug.sys vm3dmp_loader.sys vm3dmp-stats.sys vm3dver.sys vmxnet.sys vmxnet3.sys vmmouse.sys vmmemctl.sys vmusbmouse.sys vmhgfs.sys vsock.sys vmci.sys" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo for %%%%f in ^(%%DRIVER_LIST%%^) do ^( >> "%STARTUP_SCRIPT%"
echo     if exist "%%%%f" ^( >> "%STARTUP_SCRIPT%"
echo         echo      Targeting: %%%%f >> "%STARTUP_SCRIPT%"
echo         takeown /f "%%%%f" /a ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo         icacls "%%%%f" /grant Administrators:F /q ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo         del /f /q "%%%%f" ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo         if exist "%%%%f" ^( >> "%STARTUP_SCRIPT%"
echo             echo      [FAIL] Could not delete %%%%f. It might still be loaded in memory. ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo         ^) else ^( >> "%STARTUP_SCRIPT%"
echo             echo      [SUCCESS] Deleted %%%%f ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo         ^) >> "%STARTUP_SCRIPT%"
echo     ^) >> "%STARTUP_SCRIPT%"
echo ^) >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [8.] Deleting Registry Keys. ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo set "SVC_LIST=vmci vm3dmp_loader vm3dmp-debug vm3dmp-stats vmaudio vmhgfs VMMemCtl vmmouse VMRawDisk VMTools vmusbmouse vmvss vmtoolsd vmxnet vmxnet3 vsepflt" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo for %%%%S in ^(%%SVC_LIST%%^) do ^( >> "%STARTUP_SCRIPT%"
echo     sc stop "%%%%~S" ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo     powershell -NoProfile -ExecutionPolicy Bypass -Command ^"^
$p='HKLM:\SYSTEM\CurrentControlSet\Services\%%%%~S'; ^
if (Test-Path $p) { ^
$key=[Microsoft.Win32.Registry]::LocalMachine.OpenSubKey('SYSTEM\CurrentControlSet\Services\%%%%~S',[Microsoft.Win32.RegistryKeyPermissionCheck]::ReadWriteSubTree,[System.Security.AccessControl.RegistryRights]::TakeOwnership); ^
$acl=$key.GetAccessControl(); ^
$acl.SetOwner([System.Security.Principal.NTAccount]'Administrators'); ^
$key.SetAccessControl($acl); ^
$rule=New-Object System.Security.AccessControl.RegistryAccessRule('Administrators','FullControl','Allow'); ^
$acl.SetAccessRule($rule); ^
$key.SetAccessControl($acl); ^
Remove-Item -Path $p -Recurse -Force -ErrorAction SilentlyContinue ^
}^" ^>^> "%%LOGFILE%%" 2^>^&1 >> "%STARTUP_SCRIPT%"
echo ^) >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo Wildcard Services VMwareCAF - Applying same permission logic >> "%STARTUP_SCRIPT%"
echo powershell -Command "Get-Service -Name VMwareCAF* -ErrorAction SilentlyContinue | ForEach-Object { $name = $_.Name; $key = 'HKLM:\SYSTEM\CurrentControlSet\Services\' + $name; $acl = Get-Acl $key; $acl.SetOwner([System.Security.Principal.NTAccount]'Administrators'); $rule = New-Object System.Security.AccessControl.RegistryAccessRule('Administrators', 'FullControl', 'Allow'); $acl.SetAccessRule($rule); Set-Acl $key $acl; reg delete ('HKLM\SYSTEM\CurrentControlSet\Services\' + $name) /f }" ^>^> "%%LOGFILE%%" 2^>^&1 >> "%STARTUP_SCRIPT%"
echo reg delete "HKLM\SOFTWARE\VMWare, Inc." /f ^>^> "%%LOGFILE%%" 2^>^&1 >> "%STARTUP_SCRIPT%"
echo reg delete "HKLM\SOFTWARE\WOW6432Node\VMWare, Inc." /f ^>^> "%%LOGFILE%%" 2^>^&1 >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo powershell -Command "[Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path', 'Machine').Replace('C:\Program Files\VMware\VMware Tools\;', ''), 'Machine')" ^>^> "%%LOGFILE%%" 2^>^&1 >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [9] VMware files/folders cleanup ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo echo Wiping System-Wide VMware Folders... >> "%STARTUP_SCRIPT%"
echo set "SYS_FOLDERS="C:\Program Files\VMware" "C:\Program Files (x86)\VMware" "C:\Program Files\Common Files\VMware" "C:\Program Files (x86)\Common Files\VMware" "C:\ProgramData\VMware"" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo for %%%%G in ^(%%SYS_FOLDERS%%^) do ^( >> "%STARTUP_SCRIPT%"
echo     if exist %%%%G ^( >> "%STARTUP_SCRIPT%"
echo         takeown /f %%%%G /r /d y ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo         icacls %%%%G /grant Administrators:F /t /q ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo         rd /s /q %%%%G ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo         echo Deleted %%%%G ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo     ^) >> "%STARTUP_SCRIPT%"
echo ^) >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo echo removing User AppData... >> "%STARTUP_SCRIPT%"
echo for /f "tokens=*" %%%%U in ^('dir /b /ad "C:\Users"'^) do ^( >> "%STARTUP_SCRIPT%"
echo     set "USER_DIR=C:\Users\%%%%U" >> "%STARTUP_SCRIPT%"
echo     for %%%%D in ^("AppData\Local\VMware" "AppData\Roaming\VMware"^) do ^( >> "%STARTUP_SCRIPT%"
echo         if exist "^^!USER_DIR^^!\%%%%~D" ^( >> "%STARTUP_SCRIPT%"
echo             takeown /f "^^!USER_DIR^^!\%%%%~D" /r /d y ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo             icacls "^^!USER_DIR^^!\%%%%~D" /grant Administrators:F /t /q ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo             rd /s /q "^^!USER_DIR^^!\%%%%~D" ^>nul 2^>^&1 >> "%STARTUP_SCRIPT%"
echo             echo Deleted ^^!USER_DIR^^!\%%%%~D ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo         ^) >> "%STARTUP_SCRIPT%"
echo     ^) >> "%STARTUP_SCRIPT%"
echo ^) >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [10.] Preparing to delete script from Startup folder... ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo echo [%%DATE%% %%TIME%%] Self-deleting script: %%SCRIPT_PATH%% ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
::: ===========================================================================
echo echo [11.] Scheduling self-deletion... >> "%STARTUP_SCRIPT%"
echo start /b "" cmd /c "timeout /t 2 >nul & del /f /q "%%SCRIPT_PATH%%"" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo echo [12.] Cleanup complete. >> "%STARTUP_SCRIPT%"
echo echo [%%DATE%% %%TIME%%] --- CLEANUP FINISHED, REBOOTING --- ^>^> "%%LOGFILE%%" >> "%STARTUP_SCRIPT%"
echo. >> "%STARTUP_SCRIPT%"
echo shutdown /r /t 15 /f /c "VMware Deep Clean Complete. Script Deleted. Final Rebooting for Driver Flush." >> "%STARTUP_SCRIPT%"
echo exit >> "%STARTUP_SCRIPT%"
exit